[package]
name = "mdbook-include"
version = "0.1.0"
edition = "2021"

[dependencies]
mdbook = "0.4"
semver = "0.9.0"
clap = { version = "3.0", features = ["cargo"] }
serde_json = "1.0"
reqwest = "0.9.8"
url = "2.3.0"
regex = "1.7.0"